/**
 * Retrieves WordPress instance configuration by slug
 *
 * Reads configuration from NEXTPRESS_WP_INSTANCES environment variable
 * which is auto-injected by withWCR during Next.js config load.
 *
 * This approach works with both:
 * - Node.js and Edge runtimes
 * - Webpack and Turbopack bundlers
 *
 * Server-side only - not exposed to client bundle.
 */

type WPInstance = {
  wpDomain: string;
  wpProtocol: string;
  wpHomeUrl: string;
  wpSiteUrl: string;
};

type WPInstances = Record<string, WPInstance>;

let cachedInstances: WPInstances | null = null;

/**
 * Loads WordPress instance configurations from environment variable
 */
function loadInstances(): WPInstances {
  if (cachedInstances) {
    return cachedInstances;
  }

  if (!process.env.NEXTPRESS_WP_INSTANCES) {
    throw new Error(
      'NEXTPRESS_WP_INSTANCES environment variable not found. Make sure withWCR is properly configured in next.config.js'
    );
  }

  try {
    cachedInstances = JSON.parse(process.env.NEXTPRESS_WP_INSTANCES);
    return cachedInstances!;
  } catch (error) {
    throw new Error(
      'Failed to parse NEXTPRESS_WP_INSTANCES environment variable. This is auto-generated by withWCR.'
    );
  }
}

/**
 * Gets a WordPress instance configuration by slug
 *
 * @param slug - The instance slug to retrieve
 * @returns The WordPress instance configuration
 * @throws Error if the slug is not found
 */
export function getWPInstance(slug: string): WPInstance {
  const instances = loadInstances();
  const instance = instances[slug];

  if (!instance) {
    const availableSlugs = Object.keys(instances).join(', ');
    throw new Error(
      `WordPress instance "${slug}" not found. Available instances: ${availableSlugs}`
    );
  }

  return instance;
}

/**
 * Gets all WordPress instance configurations
 */
export function getAllWPInstances(): WPInstances {
  return loadInstances();
}

/**
 * Gets all WordPress instance slugs
 */
export function getInstanceSlugs(): string[] {
  const instances = loadInstances();
  return Object.keys(instances);
}
